import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.UnknownHostException;
import java.util.LinkedList;

public class QuizRegPanel extends JPanel {

        /**
         * Creates new form NewJPanel
         */
        public QuizRegPanel(JFrame frame) {
            motherFrame=frame;
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jLabel1 = new JLabel();
            jLabel2 = new JLabel();
            jTextField1 = new JTextField();
            jLabel3 = new JLabel();
            jTextField2 = new JTextField();
            jButton1 = new JButton();

            setBackground(new java.awt.Color(60, 80, 100));

            jLabel1.setIcon(new ImageIcon(getClass().getResource("14.png"))); // NOI18N

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(204, 204, 204));
            jLabel2.setText("User Id");

            jTextField1.setBackground(new java.awt.Color(80, 100, 120));
            jTextField1.setForeground(new java.awt.Color(204, 204, 204));
            jTextField1.setToolTipText("Enter your student id");

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(204, 204, 204));
            jLabel3.setText("Email");

            jTextField2.setBackground(new java.awt.Color(80, 100, 120));
            jTextField2.setForeground(new java.awt.Color(204, 204, 204));
            jTextField2.setToolTipText("test result will be sent to this email address");

            jButton1.setForeground(new java.awt.Color(239, 105, 55));
            jButton1.setText("Next");
            jButton1.addActionListener(new RegHandler());

            GroupLayout layout = new GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(208, 208, 208)
                                                    .addComponent(jLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(187, 187, 187)
                                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel3))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jTextField1)
                                                                    .addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))))
                                    .addContainerGap(213, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34))
            );
        }// </editor-fold>


        // Variables declaration - do not modify
        private JButton jButton1;
        private JLabel jLabel1;
        private JLabel jLabel2;
        private JLabel jLabel3;
        private JTextField jTextField1;
        private JTextField jTextField2;
        private JFrame motherFrame;
        private String id;
        private String email;
        private String testName;
        private int timeLimit;
        private LinkedList<Test> quiz;

        // End of variables declaration
    private class RegHandler implements ActionListener{

            @Override
            public void actionPerformed(ActionEvent e) {
                id=jTextField1.getText();
                email=jTextField2.getText();

                Download download= new Download();
                try {
                    download.testDownload();
                    timeLimit=download.getTime();
                    testName=download.getId();
                } catch (UnknownHostException e1) {
                    e1.printStackTrace();
                }

                if(testName!=null&&timeLimit>0) {
                    TestReader reader = new TestReader();
                    File file = new File("Tests\\"+testName);
                    reader.readTest(file);
                    quiz = reader.getQuiz();


                    QuestionPanel questionQuiz = new QuestionPanel(quiz,timeLimit,email,id, motherFrame);

                    motherFrame.remove(QuizRegPanel.this);
                    motherFrame.add(questionQuiz);
                    motherFrame.pack();
                }
                else {
                    JOptionPane.showMessageDialog(QuizRegPanel.this,"Error Occured, Something went wrong please try again!");
                    motherFrame.remove(QuizRegPanel.this);
                    motherFrame.add(new Welcome(motherFrame));
                    motherFrame.pack();
                }

            }
        }
    }


